secrets:
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
  secret_key:
    file: ./secrets/secret_key.txt

services:
  loki:
    image: grafana/loki:2.9.0
    container_name: azuraforge_loki
    ports: ["3100:3100"]
    volumes:
      - ./config/loki-config.yml:/etc/loki/config.yaml
    command: -config.file=/etc/loki/config.yaml
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  promtail:
    image: grafana/promtail:2.9.0
    container_name: azuraforge_promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    restart: always
    depends_on:
      loki:
        condition: service_healthy

  grafana:
    image: grafana/grafana-oss:10.2.2
    container_name: azuraforge_grafana
    ports: ["3000:3000"]
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PROVISIONING_PATH=/etc/grafana/provisioning
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    restart: always
    depends_on:
      loki:
        condition: service_healthy

  redis:
    image: redis:alpine
    container_name: azuraforge_redis
    ports: ["6379:6379"]
    volumes:
      - redis_data:/data
    logging: &default-logging
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    image: postgres:15-alpine
    container_name: azuraforge_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$(cat /run/secrets/postgres_user) -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    secrets:
      - postgres_user
      - postgres_password
    logging: *default-logging

  api:
    container_name: azuraforge_api
    build:
      context: ../api
      dockerfile: Dockerfile
    ports: ["8000:8000"]
    volumes:
      - ../api:/app
      - ${REPORTS_DIR:-./reports}:/app/reports
      - ${CACHE_DIR:-./.cache}:/app/.cache
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - REPORTS_DIR=/app/reports
      - CACHE_DIR=/app/.cache
    secrets:
      - postgres_user
      - postgres_password
      - secret_key
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn azuraforge_api.main:app --host 0.0.0.0 --port 8000 --reload
    logging: *default-logging

  worker:
    container_name: azuraforge_worker
    build:
      context: ../worker
      dockerfile: Dockerfile
    volumes:
      - ../worker:/app
      - ${REPORTS_DIR:-./reports}:/app/reports
      - ${CACHE_DIR:-./.cache}:/app/.cache
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - REPORTS_DIR=/app/reports
      - CACHE_DIR=/app/.cache
      - AZURAFORGE_DEVICE=${AZURAFORGE_DEVICE:-cpu}
    secrets:
      - postgres_user
      - postgres_password
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: python3 -m azuraforge_worker.main
    logging: *default-logging

  dashboard:
    container_name: azuraforge_dashboard
    build:
      context: ../dashboard
      dockerfile: Dockerfile
    command: npm run dev -- --host 0.0.0.0
    ports: ["5173:5173"]
    volumes:
      # SADECE kod değişikliklerinin anında yansıması için ana proje klasörünü mount ediyoruz.
      # node_modules klasörü, imajın içinden geleceği için artık burada belirtilmiyor.
      - ../dashboard:/app
      # Docker'a, /app/node_modules klasörüne DOKUNMAMASINI söylüyoruz.
      # Bu isimsiz volume, host'taki klasörün imajdaki klasörü ezmesini engeller.
      - /app/node_modules
    depends_on:
      - api
    logging: *default-logging


volumes:
  redis_data:
  postgres_data:
  grafana_data:
  # DÜZELTME: İsimsiz volume'ler yerine isimlendirilmiş volume'ler kullanıyoruz.
  # Bu, docker-compose'un gereksiz 'platform_reports_data' gibi isimler üretmesini engeller.
  reports_data:
  cache_data: